

KPLIB_Units_Override_car_crew_Loadout = [["rhs_weap_akms","rhs_acc_dtkakm","rhs_acc_2dpZenit","",["rhs_30Rnd_762x39mm",30],[],""],[],[],["eaf_full_private_inf_uniform",[["ACE_EntrenchingTool",1],["ACE_fieldDressing",5],["ACE_quikclot",5],["ACE_splint",2],["ACE_tourniquet",1],["ACE_EarPlugs",1],["ACE_packingBandage",2],["eaf_beef_can",1],["eaf_foul_can",2],["eaf_fig_jam",2],["eaf_water_bottle",1],["ACE_Canteen",1]]],["rhsusf_mbav",[["rhs_30Rnd_762x39mm_polymer",1,30]]],[],"eaf_inf_patrolcap","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","tf_anprc152_2","ItemCompass","ItemWatch",""]];
KPLIB_Units_Override_tank_crew_Loadout = [["rhs_weap_akms","rhs_acc_dtkakm","rhs_acc_2dpZenit","",["rhs_30Rnd_762x39mm",30],[],""],[],[],["eaf_full_private_cav_uniform",[["ACE_EntrenchingTool",1],["ACE_fieldDressing",5],["ACE_quikclot",5],["ACE_splint",2],["ACE_tourniquet",1],["ACE_EarPlugs",1],["ACE_packingBandage",2],["eaf_beef_can",1],["eaf_foul_can",2],["eaf_fig_jam",2],["eaf_water_bottle",1],["ACE_Canteen",1]]],["rhsusf_mbav_light",[["rhs_30Rnd_762x39mm_polymer",3,30],["SmokeShell",4,1]]],["eaf_private_bag",[["ToolKit",1]]],"rhsusf_cvc_ess","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","tf_anprc152_2","ItemCompass","ItemWatch",""]];

KPLIB_Units_Override_crew_Names = [Custom_First_Names,Custom_Last_Names];


_farooqAliDrivers_loadout = [["uk3cb_weap_akmn_1p29_sup","rhs_acc_pbs1","","rhs_acc_1p29",["rhs_30Rnd_762x39mm",30],[],""],[],["UK3CB_BHP_sup","muzzle_snds_L","","",["UK3CB_BHP_9_13Rnd",13],[],""],["UK3CB_ARD_O_U_SF_Uniform_01",[["rhs_mag_rdg2_white",1,1],["rhs_mag_rdg2_black",1,1],["rhs_mag_rgd5",2,1],["UK3CB_BHP_9_13Rnd",1,13]]],["UK3CB_ARD_O_V_6b5_Desert",[["ACE_EarPlugs",1],["ACE_quikclot",2],["ACE_elasticBandage",2],["ACE_packingBandage",2],["ACE_tourniquet",2],["ACE_splint",2],["ACE_morphine",1],["ACE_epinephrine",1],["ACE_adenosine",1],["rhs_30Rnd_762x39mm",3,30]]],["UK3CB_ARD_O_B_LargePack_RIF",[["ACE_quikclot",2],["ACE_elasticBandage",2],["ACE_packingBandage",2],["ACE_tourniquet",2],["ACE_splint",2],["ACE_morphine",1],["ACE_epinephrine",1],["ACE_adenosine",1],["rhs_30Rnd_762x39mm",3,30],["UK3CB_BHP_9_13Rnd",1,13]]],"","",[],["ItemMap","","ItemRadio","ItemCompass","ItemWatch","UK3CB_PVS5A"]];
//[classname,customname,custom_first_names,custom_last_names,loadout]
KPLIB_Units_Override = [
	


	["B_EGSAKA_Operator_D_01",
	"Egyptian Infantry",
	Custom_First_Names,Custom_Last_Names,
	[["uk3cb_ak47n","rhs_acc_dtkakm","rhs_acc_2dpZenit","rhs_acc_ekp8_02",["rhs_30Rnd_762x39mm",30],[],""],[],[],["eaf_full_private_inf_uniform",[["ACE_EntrenchingTool",1],["ACE_fieldDressing",15],["ACE_quikclot",10],["ACE_splint",3],["ACE_tourniquet",2],["ACE_EarPlugs",1],["ACE_CableTie",2],["ACE_packingBandage",4]]],["rhsusf_mbav_rifleman",[["eaf_beef_can",1],["eaf_foul_can",2],["eaf_fig_jam",2],["eaf_water_bottle",1],["ACE_Canteen",1],["rhs_30Rnd_762x39mm",7,30],["SmokeShell",3,1],["ACE_M84",1,1],["HandGrenade",1,1]]],[],"eaf_metal_helmet","G_Tactical_Black",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","tf_anprc152_1","ItemCompass","ItemWatch",""]]
	],

	//obfor
	["UK3CB_ARD_O_JNR_OFF","",[],[],[["rhs_weap_ak74n_2","rhs_acc_dtk1983","","",["rhs_30Rnd_545x39_7N6M_plum_AK",30],[],""],[],["UK3CB_BHP","","","",["UK3CB_BHP_9_13Rnd",13],[],""],["UK3CB_ARD_O_U_CombatUniform_01",[["rhs_mag_rdg2_white",1,1],["rhs_mag_rdg2_black",1,1],["rhs_mag_rgd5",2,1],["UK3CB_BHP_9_13Rnd",1,13]]],["UK3CB_ARD_O_V_6b23_vydra_3m_TAN",[["ACE_EarPlugs",1],["ACE_quikclot",2],["ACE_elasticBandage",2],["ACE_packingBandage",2],["ACE_tourniquet",2],["ACE_splint",2],["ACE_morphine",1],["ACE_epinephrine",1],["ACE_adenosine",1],["rhs_30Rnd_545x39_7N6M_plum_AK",3,30]]],["UK3CB_ARD_O_B_Radio",[]],"UK3CB_ARD_O_H_Patrolcap","",[],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch",""]]],
	["UK3CB_ARD_O_OFF","",[],[],[[],[],["rhs_weap_rsp30_red","","","",["rhs_mag_rsp30_red",1],[],""],["UK3CB_ARD_O_U_CombatUniform_01",[["ACE_EarPlugs",1],["ACE_quikclot",2],["ACE_elasticBandage",1],["ACE_packingBandage",1],["ACE_tourniquet",1],["ACE_splint",1],["ACE_morphine",1],["ACE_epinephrine",1],["ACE_adenosine",1],["rhs_mag_rdg2_white",1,1],["UK3CB_BHP_9_13Rnd",2,13]]],["rhs_vest_pistol_holster",[]],["UK3CB_ARD_O_B_Radio",[]],"UK3CB_ARD_O_H_Beret_OFF","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch",""]]],
	["UK3CB_ARD_O_TL","",[],[],[["rhs_weap_ak74n_2","rhs_acc_dtk1983","","",["rhs_30Rnd_545x39_7N6M_plum_AK",30],[],""],[],["UK3CB_BHP","","","",["UK3CB_BHP_9_13Rnd",13],[],""],["UK3CB_ARD_O_U_CombatUniform_01",[["rhs_mag_rdg2_white",1,1],["rhs_mag_rdg2_black",1,1],["rhs_mag_rgd5",2,1],["UK3CB_BHP_9_13Rnd",1,13]]],["UK3CB_ARD_O_V_6b23_vydra_3m_TAN",[["ACE_EarPlugs",1],["ACE_quikclot",2],["ACE_elasticBandage",2],["ACE_packingBandage",2],["ACE_tourniquet",2],["ACE_splint",2],["ACE_morphine",1],["ACE_epinephrine",1],["ACE_adenosine",1],["rhs_30Rnd_545x39_7N6M_plum_AK",3,30]]],["UK3CB_ARD_O_B_Radio",[]],"UK3CB_ARD_O_H_Patrolcap","",["Binocular","","","",[],[],""],["ItemMap","","ItemRadio","ItemCompass","ItemWatch",""]]],
	//paratroper
	[opfor_paratrooper,"",[],[],[["uk3cb_weap_akm_sup","rhs_acc_pbs1","","",["rhs_30Rnd_762x39mm",30],[],""],["rhs_weap_rpg7","","","rhs_acc_pgo7v3",["rhs_rpg7_PG7VL_mag",1],[],""],["UK3CB_BHP_sup","muzzle_snds_L","","",["UK3CB_BHP_9_13Rnd",13],[],""],["UK3CB_ARD_O_U_SF_Uniform_01",[["ACE_elasticBandage",10],["UK3CB_AK47_30Rnd_Magazine_G",1,30],["SmokeShell",1,1],["MS_Strobe_Mag_2",2,1]]],["UK3CB_ARD_O_V_6b5_Desert",[["AMP_Breaching_Charge_Mag",2,1],["UK3CB_AK47_30Rnd_Magazine_G",2,30],["HandGrenade",1,1]]],["B_Parachute",[]],"","",[],["ItemMap","","ItemRadio","ItemCompass","ItemWatch","UK3CB_PVS5A"]]],
	//snipers and spotter SF
	[opfor_sf_sniper,"",[],[],[["rhs_weap_svdp_wd_npz","rhs_acc_tgpv2","","ACE_optic_LRPS_PIP",["ACE_10Rnd_762x54_Tracer_mag",4],[],""],[],["UK3CB_BHP_sup","muzzle_snds_L","","",["UK3CB_BHP_9_13Rnd",13],[],""],["U_I_FullGhillie_ard",[]],["UK3CB_ARD_O_V_6b5_Sniper_Desert",[["ACE_RangeCard",1],["ACE_ATragMX",1],["rhs_mag_rdg2_white",1,1],["rhs_mag_rdg2_black",1,1],["rhs_mag_rgd5",2,1],["SmokeShellBlue",1,1],["SmokeShellOrange",1,1],["O_IR_Grenade",1,1]]],["UK3CB_ARD_O_B_LargePack_RIF_TAN",[["ACE_EarPlugs",2],["ACE_quikclot",4],["ACE_elasticBandage",4],["ACE_packingBandage",4],["ACE_tourniquet",4],["ACE_splint",4],["ACE_morphine",2],["ACE_epinephrine",2],["ACE_adenosine",2],["UK3CB_BHP_9_13Rnd",2,13],["10Rnd_762x54_Mag",25,10],["ACE_10Rnd_762x54_Tracer_mag",5,10]]],"","UK3CB_G_Balaclava2_DES",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","tf_fadak_1","ItemCompass","ItemWatch",""]]],
	[opfor_sf_sharpshooter,"",[],[],[["uk3cb_weap_akmn_1p29_sup","rhs_acc_pbs1","","rhs_acc_1p29",["rhs_30Rnd_762x39mm",30],[],""],[],["UK3CB_BHP_sup","muzzle_snds_L","","",["UK3CB_BHP_9_13Rnd",13],[],""],["U_I_FullGhillie_ard",[["rhs_mag_rdg2_white",1,1],["rhs_mag_rdg2_black",1,1],["rhs_mag_rgd5",2,1],["UK3CB_BHP_9_13Rnd",1,13]]],["UK3CB_ARD_O_V_6b5_Sniper_Desert",[["ACE_EarPlugs",1],["ACE_quikclot",2],["ACE_elasticBandage",2],["ACE_packingBandage",2],["ACE_tourniquet",2],["ACE_splint",2],["ACE_morphine",1],["ACE_epinephrine",1],["ACE_adenosine",1],["rhs_30Rnd_762x39mm",3,30]]],["UK3CB_ARD_O_B_LargePack_RIF_TAN",[["ACE_quikclot",2],["ACE_elasticBandage",2],["ACE_packingBandage",2],["ACE_tourniquet",2],["ACE_splint",2],["ACE_morphine",1],["ACE_epinephrine",1],["ACE_adenosine",1],["rhs_30Rnd_762x39mm",3,30],["UK3CB_BHP_9_13Rnd",1,13],["rhs_10Rnd_762x54mmR_7N1",5,10]]],"","UK3CB_G_Balaclava_DES",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch",""]]],

	//Farooq Ali
	["O_officer_F","",[],[],[[],[],[],["UK3CB_ARD_B_U_CombatUniform_01",[]],[],[],"rhs_beret_milp","",[],["ItemMap","","","ItemCompass","tf_microdagr",""]]],
	//Farooq Ali Drivers 
	["rhs_msv_driver_armored","",[],[],_farooqAliDrivers_loadout],
	["rhs_msv_grenadier","",[],[],_farooqAliDrivers_loadout],
	//Abu Nawaf 
	["O_Officer_Parade_Veteran_F","",[],[],[["rhs_weap_MP44","","","",["rhsgref_30Rnd_792x33_SmE_StG",30],[],""],[],[],["UK3CB_TKM_B_U_06_B",[]],[],[],"UK3CB_H_Beret_Officer_Red","G_Aviator",[],["ItemMap","","","ItemCompass","tf_microdagr",""]]],
	//Michael Cohen
	["O_Officer_Parade_F","",[],[],[[],[],[],["U_C_FormalSuit_01_tshirt_black_F",[]],[],[],"","G_Aviator",[],["ItemMap","ItemGPS","tf_anprc148jem_2","ItemCompass","ItemWatch",""]]],
	//Michael Cohen Bodyguard
	["O_G_Soldier_universal_F","",[],[],[["rhs_weap_akmn_gp25","rhs_acc_pbs1","","",["rhs_30Rnd_762x39mm",30],[],""],[],["rhs_weap_pb_6p9","rhs_acc_6p9_suppressor","","",["rhs_mag_9x18_8_57N181S",8],[],""],["U_O_R_Gorka_01_black_F",[]],["UK3CB_TKP_I_V_6Sh92_Blk",[]],["UK3CB_B_Small_Pack",[]],"UK3CB_H_Beanie_02_BLK","G_Bandanna_blk",["Binocular","","","",[],[],""],["ItemMap","","tf_anprc148jem_2","ItemCompass","ItemWatch","NVGoggles_OPFOR"]]],
	//Michael Cohen driver
	["UK3CB_AAF_O_SF_RIF_1","",[],[],[["rhs_weap_akmn_gp25","rhs_acc_pbs1","","",["rhs_30Rnd_762x39mm",30],[],""],[],["rhs_weap_pb_6p9","rhs_acc_6p9_suppressor","","",["rhs_mag_9x18_8_57N181S",8],[],""],["U_O_R_Gorka_01_black_F",[]],["UK3CB_TKP_I_V_6Sh92_Blk",[]],["UK3CB_B_Small_Pack",[]],"UK3CB_H_Beanie_02_BLK","G_Bandanna_blk",["Binocular","","","",[],[],""],["ItemMap","","tf_anprc148jem_2","ItemCompass","ItemWatch","NVGoggles_OPFOR"]]],
	//Haftar Jafar
	["B_T_Officer_F","",[],[],[[],[],[],["LOP_U_Fatigue_BDU_ATACS_AU_02",[]],[],[],"rhssaf_beret_green","",[],["ItemMap","","","ItemCompass","tf_microdagr",""]]]
];